"""initial creator schema

Revision ID: e6f17c3739e9
Revises: 
Create Date: 2026-07-31 01:00:03.233354
"""
from alembic import op
import sqlalchemy as sa
import app.database  # noqa: F401 — requis : les colonnes ci-dessous utilisent app.database.GUID()


revision = 'e6f17c3739e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('tenant_id', app.database.GUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=False),
    sa.Column('tone_of_voice', sa.String(length=500), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_tenant_id'), 'creators', ['tenant_id'], unique=True)
    op.create_index(op.f('ix_creators_user_id'), 'creators', ['user_id'], unique=True)
    op.create_table('portfolios',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tenant_id', app.database.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_slug'), 'portfolios', ['slug'], unique=True)
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('portfolio_blocks',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('portfolio_id', app.database.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'position', name='uq_block_portfolio_position')
    )
    op.create_index(op.f('ix_portfolio_blocks_portfolio_id'), 'portfolio_blocks', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_blocks_portfolio_id'), table_name='portfolio_blocks')
    op.drop_table('portfolio_blocks')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_slug'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_creators_user_id'), table_name='creators')
    op.drop_index(op.f('ix_creators_tenant_id'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
